// Generated by CoffeeScript 1.8.0
var showDoctorSelector, showQrSelector;

this.initPage = function() {
  $A().app().preference("doctor_group_id").then(function(res) {
    if ((res != null) && res !== "") {
      return $A().app().preference("sickness_id").then(function(r1) {
        if ((r1 != null) && r1 !== "") {
          return $A().app().openPage({
            page_name: "page_index_tab",
            params: {},
            close_option: "close"
          });
        } else {
          return showDoctorSelector(res);
        }
      });
    } else {
      return showQrSelector();
    }
  });
  return $A().page("page_select_doctor").onResult(function(data) {
    var doctor_group_id;
    if (data.type === "qrcaputre") {
      doctor_group_id = data.codeString;
      $A().app().callApi({
        method: "user/users/doctorinfo_edit",
        doctor_group_id: doctor_group_id
      }).then(function(r1) {
        $A().app().preference({
          key: "doctor_group_name",
          value: r1.name
        });
        $A().app().preference({
          key: "doctor_group_id",
          value: doctor_group_id
        });
        $A().app().makeToast("请选择医生及诊断");
        return showDoctorSelector(doctor_group_id);
      });
    }
    return "_false";
  });
};

showQrSelector = function() {
  $(".selqrcode").show();
  return $(".qrcode").tap(function() {
    return $A().page("page_select_doctor").openQRCapture({});
  });
};

showDoctorSelector = function(doctor_group_id) {
  $(".seldoctor").show();
  $(".selqrcode").hide();
  $A().app().preference("doctor_group_name").then(function(r1) {
    return $(".seldoctor h3").html(r1);
  });
  $(".doctorsubmit").tap(function() {
    var doctor_id, sickness_id;
    doctor_id = $("#seloptions1 input:checked").val();
    sickness_id = $("#seloptions2 input:checked").val();
    if (doctor_id === "" || sickness_id === "") {
      return alert("请选择医生及诊断");
    }
    return $A().app().callApi({
      method: "user/users/doctorinfo_edit",
      sickness_id: sickness_id,
      doctor_id: doctor_id,
      cacheTime: 0
    }).then(function(res) {
      $A().app().preference({
        key: "sickness_id",
        value: sickness_id
      });
      $A().app().preference({
        key: "doctor_id",
        value: doctor_id
      });
      return $A().app().openPage({
        page_name: "page_home",
        params: {},
        close_option: "close"
      });
    });
  });
  $A().app().callApi({
    method: "content/doctor_groups/doctors",
    doctor_group_id: doctor_group_id,
    cacheTime: 0
  }).then(function(r2) {
    var html, item, _i, _len, _ref;
    html = "";
    _ref = r2.result;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      html = html + ("<span ><input type=\"radio\" name=\"doctors\" id=\"" + item.id + "\" value=\"" + item.id + "\"/> <label for=\"" + item.id + "\">" + item.title + "</label></span>");
    }
    return $("#seloptions1").html(html);
  });
  return $A().app().callApi({
    method: "content/doctor_groups/sickness",
    doctor_group_id: doctor_group_id,
    cacheTime: 0
  }).then(function(r2) {
    var html, item, _i, _len, _ref;
    html = "";
    _ref = r2.sorts;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      html = html + ("<span ><input type=\"radio\" name=\"sickness\" id=\"" + item.id + "\" value=\"" + item.id + "\"/> <label for=\"" + item.id + "\">" + item.cnname + "</label></span>");
    }
    return $("#seloptions2").html(html);
  });
};
